### ISSUE TITLE
[Feature] Add button for resizing images

### ISSUE THREAD

**Issue by kevinanielsen** [kevinanielsen/go-fast-cdn#90]
**Is your feature request related to a problem? Please describe.** <br>
A button for resizing an image on the UI using the `/api/cdn/resize/image` endpoint

**Describe the solution you'd like**<br>
A button, that opens a modal, where you can input desired height and width and a confirmation.

**Describe alternatives you've considered**<br>
N/A

**Additional context**<br>
N/A

**Comment by sumon-chandra** [comment]
Hi @kevinanielsen, I want to work on this.  Can you please describe to me, where the button should be?  And I don't find ``/api/cdn/resize/image`` endpoint in this project. Where is this endpoint located?

**Comment by kevinanielsen** [comment]
@sumon-chandra this button should be located along with the rename and delete buttons for the file cards - the endpoint is located in the `src/router/api.go` file.

Will assign you to the issue now 😃

**Comment by sumon-chandra** [comment]
@kevinanielsen sorry to say that I've got some major issues in this project. 
### - The contents aren't loaded on fetching. 
### - I've tried to run the backend, but I couldn't.

![image](https://github.com/kevinanielsen/go-fast-cdn/assets/80484412/41c2a6b3-3c05-43c0-a01d-fb766da466c1)
![image](https://github.com/kevinanielsen/go-fast-cdn/assets/80484412/80383214-e895-41e3-b158-041ad9a2c6a2)

Can you please provide me the instructions on how I can get the contents so that I can work on it?
**I love working on challenging things and I'm curious to work on this.**

**Comment by kevinanielsen** [comment]
@sumon-chandra I am sorry it has not been easy to work on this.

To run the backend, make sure you are in the root of the project and that you have Go installed. Then run `go mod install` and then `go run .` this will spin up the backend.

Once the backend is running, it should be straight forward to develop the frontend :) Let me know if your issues persist

**Comment by luckramos** [comment]
Hey @kevinanielsen! Is this still open? Would love to work on this!

**Comment by kevinanielsen** [comment]
> Hey @kevinanielsen! Is this still open? Would love to work on this!
@luckramos 

For sure, assigning you now!

**Comment by samarthasthan** [comment]
Hey @kevinanielsen, let @luckramos try this. Otherwise i would like to work on this.

**Comment by luckramos** [comment]
#142

**Comment by luckramos** [comment]
Hey @kevinanielsen! I just created a PR for this issue #142
